#!/usr/bin/env python

env = Environment()
env['CPPFLAGS'] = '-g -O0 '
env['LIBS'] = 'profiler'
env['LIBPATH'] = '/usr/local/lib'
env['CPUPROFILE']='foo.prof'
env.Program('tenc', source=['adpcm.c', 'tenc.c'])
env.Program('tdec', source=['adpcm.c', 'tdec.c'])
